#:import LauncherScreen screens.launcher_screen.LauncherScreen
#:import MainMenuScreen screens.main_menu_screen.MainMenuScreen
#:import ConfigScreen screens.config_screen.ConfigScreen
#:import DownloadScreen screens.download_screen.DownloadScreen
#:import CountScreen screens.count_screen.CountScreen
#:import AuditScreen screens.audit_screen.AuditScreen
#:import CorrectionScreen screens.correction_screen.CorrectionScreen
#:import SyncScreen screens.sync_screen.SyncScreen
#:import CountStockMenuScreen countstock.screens.CountStockMenuScreen
#:import CountStockConfigScreen countstock.screens.CountStockConfigScreen
#:import CountStockImportScreen countstock.screens.CountStockImportScreen
#:import CountStockScanScreen countstock.screens.CountStockScanScreen
#:import CountStockExportScreen countstock.screens.CountStockExportScreen

ScreenManager:
    LauncherScreen:
        name: "launcher"
    MainMenuScreen:
        name: "main_menu"
    ConfigScreen:
        name: "config"
    DownloadScreen:
        name: "download"
    CountScreen:
        name: "count"
    AuditScreen:
        name: "audit"
    CorrectionScreen:
        name: "correction"
    SyncScreen:
        name: "sync"
    CountStockMenuScreen:
        name: "countstock_menu"
    CountStockConfigScreen:
        name: "countstock_config"
    CountStockImportScreen:
        name: "countstock_import"
    CountStockScanScreen:
        name: "countstock_scan"
    CountStockExportScreen:
        name: "countstock_export"
