<ProductCard>:


    orientation:"vertical"


    padding:"10dp"


    size_hint_y:None


    height:"120dp"



    MDLabel:


        text:

            root.item_code



    MDLabel:


        text:

            root.item_name



    MDLabel:


        text:

            "Location : " + root.location



    MDLabel:


        text:

            "Qty : " + root.qty



    MDLabel:


        text:

            root.barcode